### ISSUE TITLE
Add EdgeFromNormalMap

### ISSUE THREAD

**Issue by campi3d** [campi3d/MARI-Extension-Pack#74]

**Comment by bneall** [comment]
Do you have any implementation or information on this procedure? I've been looking for information regarding this extraction process.

**Comment by campi3d** [comment]
Yeah I already made it work to allow the user to add a normal map mix to polysurface curvature. Suffers from the same issue as the main node for the lack of blurring. I'll make a standalone version for the next release.

**Comment by campi3d** [comment]
It's in the latest commit of the Mari3 Branch if you ate interested and will add the standalone sometime this weekend.

**Comment by campi3d** [comment]
Pushed to dev for 2.1 release: 9db78ef0f666cd7f22b4a628c631bf3a59a8fb69
